# Site settings
title: Ans
description: Anti-fragile & Scale-up
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ans
user_description: We aim to be anti-fragile and focused on scaling up. Our first business venture is the launch of the iOS app 'QuickTodo'.
user_title: iOS App Development
email: anskrr7@gmail.com
# twitter_username: lorem_ipsum
instagram_username: antifragile.scaleup
# facebook_username: mauricio.urraco
# linkedin_username: murraco
github_username:  ans-bruce
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

